// prettier-ignore
export const instrumentTags: Record<string, string | string[]>[] = [
    { tag: ['calung', 'cal', 'ca'], addition: [''], positions: ['CALUNG'] },
    { tag: ['cengceng', 'ceng', 'ce'], addition: [''], positions: ['CENGCENG'] },
    { tag: ['gangsa', 'gang', 'ga'], addition: [''], positions: ['PEMADE_POLOS', 'KANTILAN_POLOS', 'PEMADE_SANGSIH', 'KANTILAN_SANGSIH'] },
    { tag: ['gangsa', 'ga'], addition: ['polos', 'po', 'p'], positions: ['PEMADE_POLOS', 'KANTILAN_POLOS'] },
    { tag: ['gangsa', 'ga'], addition: ['sangsih', 'sang', 'sa', 's'], positions: ['PEMADE_SANGSIH', 'KANTILAN_SANGSIH'] },
    { tag: ['genderrambat', 'gender', 'gen', 'ge'], addition: [], positions: ['GENDERRAMBAT'] },
    { tag: ['gongs', 'gong', 'go'], addition: [''], positions: ['GONGS'] },
    { tag: ['gying', 'gy'], addition: [''], positions: ['UGAL'] },
    { tag: ['jegogan', 'jegog', 'jeg', 'je'], addition: [''], positions: ['JEGOGAN'] },
    { tag: ['jublag', 'jub', 'ju', 'calung', 'cal', 'ca'], addition: [''], positions: ['CALUNG'] },
    { tag: ['kantilan', 'kan', 'ka'], addition: [''], positions: ['KANTILAN_POLOS', 'KANTILAN_SANGSIH'] },
    { tag: ['kantilan', 'kan', 'ka'], addition: ['polos', 'pol', 'po', 'p'], positions: ['KANTILAN_POLOS'] },
    { tag: ['kantilan', 'kan', 'ka'], addition: ['sangsih', 'sang', 'sa', 's'], positions: ['KANTILAN_SANGSIH'] },
    { tag: ['kempli', 'kem', 'ke'], addition: [''], positions: ['KEMPLI'] },
    { tag: ['kendang', 'kend', 'kd'], addition: [''], positions: ['KENDANG'] },
    { tag: ['pemade', 'pem', 'pe'], addition: [''], positions: ['PEMADE_POLOS', 'PEMADE_SANGSIH'] },
    { tag: ['pemade', 'pem', 'pe'], addition: ['polos', 'pol', 'po', 'p'], positions: ['PEMADE_POLOS'] },
    { tag: ['pemade', 'pem', 'pe'], addition: ['sangsih', 'sang', 'sa', 's'], positions: ['PEMADE_SANGSIH'] },
    { tag: ['penyacah', 'peny', 'pen'], addition: [''], positions: ['PENYACAH'] },
    { tag: ['reyong', 'rey', 're'], addition: [''], positions: ['REYONG_1', 'REYONG_2', 'REYONG_3', 'REYONG_4'] },
    { tag: ['reyong', 'rey', 're'], addition: ['1'], positions: ['REYONG_1'] },
    { tag: ['reyong', 'rey', 're'], addition: ['2'], positions: ['REYONG_2'] },
    { tag: ['reyong', 'rey', 're'], addition: ['3'], positions: ['REYONG_3'] },
    { tag: ['reyong', 'rey', 're'], addition: ['4'], positions: ['REYONG_4'] },
    { tag: ['reyong', 'rey', 're'], addition: ['12', '1+2'], positions: ['REYONG_1', 'REYONG_2'] },
    { tag: ['reyong', 'rey', 're'], addition: ['13', '1+3'], positions: ['REYONG_1', 'REYONG_3'] },
    { tag: ['reyong', 'rey', 're'], addition: ['24', '2+4'], positions: ['REYONG_2', 'REYONG_4'] },
    { tag: ['reyong', 'rey', 're'], addition: ['34', '3+4'], positions: ['REYONG_3', 'REYONG_4'] },
    { tag: ['suling', 'sul', 'su'], addition: [''], positions: ['SULING'] },
    { tag: ['trompong', 'tromp', 'tro', 'tr'], addition: [''], positions: ['TROMPONG'] },
    { tag: ['ugal', 'ug'], addition: [''], positions: ['UGAL'] }
]
