// prettier-ignore
export const instrumentTags: Record<string, string | string[]>[] = [
    { pos_tag: ['calung', 'cal', 'ca'], specification_tag: [''], positions: ['CALUNG'] },
    { pos_tag: ['cengceng', 'ceng', 'ce'], specification_tag: [''], positions: ['CENGCENG'] },
    { pos_tag: ['gangsa', 'ga'], specification_tag: [''], positions: ['PEMADE_POLOS', 'KANTILAN_POLOS', 'PEMADE_SANGSIH', 'KANTILAN_SANGSIH'] },
    { pos_tag: ['gangsa', 'ga'], specification_tag: ['polos', 'po', 'p'], positions: ['PEMADE_POLOS', 'KANTILAN_POLOS'] },
    { pos_tag: ['gangsa', 'ga'], specification_tag: ['sangsih', 'sang', 'sa', 's'], positions: ['PEMADE_SANGSIH', 'KANTILAN_SANGSIH'] },
    { pos_tag: ['genderrambat', 'gender', 'gen', 'ge'], specification_tag: [], positions: ['GENDERRAMBAT'] },
    { pos_tag: ['gongs', 'gong', 'go'], specification_tag: [''], positions: ['GONGS'] },
    { pos_tag: ['gying', 'gy'], specification_tag: [''], positions: ['UGAL'] },
    { pos_tag: ['jegogan', 'jegog', 'jeg', 'je'], specification_tag: [''], positions: ['JEGOGAN'] },
    { pos_tag: ['jublag', 'jub', 'ju', 'calung', 'cal', 'ca'], specification_tag: [''], positions: ['CALUNG'] },
    { pos_tag: ['kantilan', 'kan', 'ka'], specification_tag: [''], positions: ['KANTILAN_POLOS', 'KANTILAN_SANGSIH'] },
    { pos_tag: ['kantilan', 'kan', 'ka'], specification_tag: ['polos', 'pol', 'po', 'p'], positions: ['KANTILAN_POLOS'] },
    { pos_tag: ['kantilan', 'kan', 'ka'], specification_tag: ['sangsih', 'sang', 'sa', 's'], positions: ['KANTILAN_SANGSIH'] },
    { pos_tag: ['kempli', 'kem', 'ke'], specification_tag: [''], positions: ['KEMPLI'] },
    { pos_tag: ['kendang', 'kend', 'kd'], specification_tag: [''], positions: ['KENDANG'] },
    { pos_tag: ['pemade', 'pem', 'pe'], specification_tag: [''], positions: ['PEMADE_POLOS', 'PEMADE_SANGSIH'] },
    { pos_tag: ['pemade', 'pem', 'pe'], specification_tag: ['polos', 'pol', 'po', 'p'], positions: ['PEMADE_POLOS'] },
    { pos_tag: ['pemade', 'pem', 'pe'], specification_tag: ['sangsih', 'sang', 'sa', 's'], positions: ['PEMADE_SANGSIH'] },
    { pos_tag: ['penyacah', 'peny', 'pen'], specification_tag: [''], positions: ['PENYACAH'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: [''], positions: ['REYONG_1', 'REYONG_2', 'REYONG_3', 'REYONG_4'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['1'], positions: ['REYONG_1'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['2'], positions: ['REYONG_2'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['3'], positions: ['REYONG_3'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['4'], positions: ['REYONG_4'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['12', '1+2'], positions: ['REYONG_1', 'REYONG_2'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['13', '1+3'], positions: ['REYONG_1', 'REYONG_3'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['24', '2+4'], positions: ['REYONG_2', 'REYONG_4'] },
    { pos_tag: ['reyong', 'rey', 're'], specification_tag: ['34', '3+4'], positions: ['REYONG_3', 'REYONG_4'] },
    { pos_tag: ['suling', 'sul', 'su'], specification_tag: [''], positions: ['SULING'] },
    { pos_tag: ['trompong', 'tromp', 'tromp', 'tro', 'tr'], specification_tag: [''], positions: ['TROMPONG'] },
    { pos_tag: ['ugal', 'ug'], specification_tag: [''], positions: ['UGAL'] }
]
