export const instrumentTags: Record<string, string | string[]>[] = [
    { tag: ['calung', 'cal', 'ca'], addition: [], position: 'CALUNG' },
    { tag: ['cengceng', 'ceng', 'ce'], addition: [], position: 'CENGCENG' },
    { tag: ['gangsa', 'gang', 'ga'], addition: [], position: 'PEMADE' },
    { tag: ['gangsa', 'ga'], addition: ['polos', 'po', 'p'], position: 'GANGSA_POLOS' },
    { tag: ['gangsa', 'ga'], addition: ['sangsih', 'sang', 'sa', 's'], position: 'GANGSA_SANGSIH' },
    { tag: ['genderrambat', 'gender', 'gen', 'ge'], addition: [], position: 'GENDERRAMBAT' },
    { tag: ['gongs', 'gong', 'go'], addition: [], position: 'GONGS' },
    { tag: ['gying', 'gy'], addition: [], position: 'UGAL' },
    { tag: ['jegogan', 'jegog', 'jeg', 'je'], addition: [], position: 'JEGOGAN' },
    { tag: ['jublag', 'jub', 'ju', 'calung', 'cal', 'ca'], addition: [], position: 'CALUNG' },
    { tag: ['kantilan', 'kan', 'ka'], addition: [], position: 'KANTILAN' },
    { tag: ['kantilan', 'kan', 'ka'], addition: ['polos', 'pol', 'po', 'p'], position: 'KANTILAN_POLOS' },
    { tag: ['kantilan', 'kan', 'ka'], addition: ['sangsih', 'sang', 'sa', 's'], position: 'KANTILAN_SANGSIH' },
    { tag: ['kempli', 'kem', 'ke'], addition: [], position: 'KEMPLI' },
    { tag: ['kendang', 'kend', 'kd'], addition: [], position: 'KENDANG' },
    { tag: ['pemade', 'pem', 'pe'], addition: [], position: 'PEMADE' },
    { tag: ['pemade', 'pem', 'pe'], addition: ['polos', 'pol', 'po', 'p'], position: 'PEMADE_POLOS' },
    { tag: ['pemade', 'pem', 'pe'], addition: ['sangsih', 'sang', 'sa', 's'], position: 'PEMADE_SANGSIH' },
    { tag: ['penyacah', 'peny', 'pen'], addition: [], position: 'PENYACAH' },
    { tag: ['reyong', 'rey', 're'], addition: [], position: 'REYONG' },
    { tag: ['reyong', 'rey', 're'], addition: ['1'], position: 'REYONG_1' },
    { tag: ['reyong', 'rey', 're'], addition: ['2'], position: 'REYONG_2' },
    { tag: ['reyong', 'rey', 're'], addition: ['3'], position: 'REYONG_3' },
    { tag: ['reyong', 'rey', 're'], addition: ['4'], position: 'REYONG_4' },
    { tag: ['reyong', 'rey', 're'], addition: ['12', '1+2'], position: 'REYONG_12' },
    { tag: ['reyong', 'rey', 're'], addition: ['13', '1+3'], position: 'REYONG_13' },
    { tag: ['reyong', 'rey', 're'], addition: ['24', '2+4'], position: 'REYONG_24' },
    { tag: ['reyong', 'rey', 're'], addition: ['34', '3+4'], position: 'REYONG_34' },
    { tag: ['suling', 'sul', 'su'], addition: [], position: 'SULING' },
    { tag: ['trompong', 'tromp', 'tro', 'tr'], addition: [], position: 'TROMPONG' },
    { tag: ['ugal', 'ug'], addition: [], position: 'UGAL' }
]
