import type {
    Instrument,
    InstrumentConfig,
    Orchestra,
    Position,
    PositionConfig,
    PositionGroup
} from '../types/position'

// List of available instrument groups.
// The staffs will appear in the editor in the given sequence.
// prettier-ignore
export const orchestraConfigs: Record<Orchestra, { instruments: Instrument[]; beatPosition: Position | null }> = {
    GONG_KEBYAR: {
        instruments: [ 'UGAL', 'GENDER_RAMBAT', 'TROMPONG', 'PEMADE', 'KANTILAN', 'REYONG', 'PENYACAH', 'CALUNG', 'JEGOGAN', 'GONGS', 
            'CENGCENG', 'CENGCENG_KOPYAK', 'KENDANG', 'KEMPLI'],
        beatPosition: 'KEMPLI'
    },
    BALEGANJUR: {
        instruments: ['CENGCENG_KOPYAK', 'REYONGB', 'PONGGANG', 'GONGS', 'KENDANG', 'TAWATAWA'],
        beatPosition: 'TAWATAWA'
    }
}

export const instrumentConfigs: Record<Instrument, InstrumentConfig> = {
    GONGS: { name: 'Gongs', positions: ['GONGS'] },
    KEMPLI: { name: 'Kempli', positions: ['KEMPLI'] },
    CENGCENG: { name: 'Cengceng', positions: ['CENGCENG'] },
    KENDANG: { name: 'Kendang', positions: ['KENDANG', 'KENDANG_LANANG', 'KENDANG_WADON'] },
    JEGOGAN: { name: 'Jegogan', positions: ['JEGOGAN'] },
    CALUNG: { name: 'Calung', positions: ['CALUNG'] },
    PENYACAH: { name: 'Penyacah', positions: ['PENYACAH'] },
    PEMADE: { name: 'Pemade', positions: ['PEMADE_POLOS', 'PEMADE_SANGSIH'] },
    KANTILAN: { name: 'Kantilan', positions: ['KANTILAN_POLOS', 'KANTILAN_SANGSIH'] },
    UGAL: { name: 'Ugal', positions: ['UGAL'] },
    GENDER_RAMBAT: { name: 'Gender rambat', positions: ['GENDER_RAMBAT'] },
    TROMPONG: { name: 'Trompong', positions: ['TROMPONG'] },
    REYONG: { name: 'Reyong', positions: ['REYONG_1', 'REYONG_2', 'REYONG_3', 'REYONG_4'] },
    CENGCENG_KOPYAK: { name: 'Cengceng kopyak', positions: ['CENGCENG_P', 'CENGCENG_S'] },
    REYONGB: { name: 'Reyong baleganjur', positions: ['REYONGB_1', 'REYONGB_2'] },
    TAWATAWA: { name: 'Tawa-tawa', positions: ['TAWATAWA'] },
    PONGGANG: { name: 'Ponggang', positions: ['PONGGANG'] }
}

/**
 * Possible grouping of instruments in the compact editor view.
 */
// prettier-ignore
export const positionGroups: Record<PositionGroup, InstrumentConfig> = {
    PEMADE: { positions: ['PEMADE_POLOS', 'PEMADE_SANGSIH'], name: 'Pemade' },
    KANTILAN: { positions: ['KANTILAN_POLOS', 'KANTILAN_SANGSIH'], name: 'Kantilan' },
    GANGSA_POLOS: { positions: ['PEMADE_POLOS', 'KANTILAN_POLOS'], name: 'Gangsa p' },
    GANGSA_SANGSIH: { positions: ['PEMADE_SANGSIH', 'KANTILAN_SANGSIH'], name: 'Gangsa s' },
    GANGSA: { positions: ['PEMADE_POLOS', 'PEMADE_SANGSIH', 'KANTILAN_POLOS', 'KANTILAN_SANGSIH'], name: 'Gangsa' },
    GANGSA_RANGE: {
        positions: ['PEMADE_POLOS', 'PEMADE_SANGSIH', 'KANTILAN_POLOS', 'KANTILAN_SANGSIH', 'UGAL'],
        name: 'Gangsa+Ugal'
    },
    REYONG_13: { positions: ['REYONG_1', 'REYONG_3'], name: 'reyong 1+3' },
    REYONG_24: { positions: ['REYONG_2', 'REYONG_4'], name: 'reyong 2+4' },
    REYONG: { positions: ['REYONG_1', 'REYONG_2', 'REYONG_3', 'REYONG_4'], name: 'Reyong' },
    REYONGB: { positions: ['REYONGB_1', 'REYONGB_2'], name: 'Reyong' },
    POKOK: { positions: ['CALUNG', 'JEGOGAN', 'PENYACAH'], name: 'Pokok' },
    MELODIC: {
        positions: [ 'PEMADE_POLOS', 'PEMADE_SANGSIH', 'KANTILAN_POLOS', 'KANTILAN_SANGSIH', 'UGAL', 'TROMPONG', 'GENDER_RAMBAT', 'REYONG_1', 'REYONG_3', 'REYONG_2', 'REYONG_4', 'REYONGB_1', 'REYONGB_2', 'CALUNG', 'JEGOGAN', 'PENYACAH', 'PONGGANG'],
        name: 'Melodic'
    },
    DAUN: {
        positions: [ 'PEMADE_POLOS', 'PEMADE_SANGSIH', 'KANTILAN_POLOS', 'KANTILAN_SANGSIH', 'UGAL', 'GENDER_RAMBAT', 'CALUNG', 'JEGOGAN', 'PENYACAH'],
        name: 'Daun'
    },
    PERCUSSION: {
        positions: [ 'KEMPLI', 'KENDANG', 'KENDANG_LANANG', 'KENDANG_WADON', 'REYONG_1', 'REYONG_2', 'REYONG_3', 'REYONG_4', 'CENGCENG', 'CENGCENG_P', 'CENGCENG_S', 'REYONGB_1', 'REYONGB_2', 'TAWATAWA'],
        name: 'Percussion'
    },
    CENGCENG_KOPYAK: { positions: ['CENGCENG_P', 'CENGCENG_S'], name: 'Cengceng' }
}

export const defaultBeatPosition: Position = 'KEMPLI'

//prettier-ignore
export const positionConfigs: Record<Position, PositionConfig> = {
    GONGS: {
        name: 'Gongs',
        instrument: 'GONGS',
        type: 'percussion', //TODO move type to instrument and grouping info
        svg_file: 'svg/GK_GONGS.svg',
        symbolToNoteNames: { G: ['GIR'], P: ['PUR'], T: ['TONG'] } //TODO move alphabet info to separate settings
    },
    KEMPLI: {
        name: 'Kempli',
        instrument: 'KEMPLI',
        type: 'percussion',
        svg_file: '',
        // Strictly speaking the default kempli stroke is a muted tone. However `x` is a more convenient
        // way to denote a beat stroke than `x?`. For the legong style where the kempli follows the kendang part
        // (usually in the pengawak) with open and muted strokes, kendang symbols will be added in the future
        // with corresponding kempli samples.
        // Note `X` is defined as OPEN, so `x` follows the "no modifier → OPEN" rule (muting only matters
        // for animation, and the kempli is not animated). See CLAUDE.refactor-configuration-settings.md.
        symbolToNoteNames: { x: ['X'] }
    },
    CENGCENG: {
        name: 'Cengceng',
        instrument: 'CENGCENG',
        type: 'percussion',
        svg_file: '',
        symbolToNoteNames: { x: ['X_OPEN'], 'x?': ['X_MUTED'] }
    },
    KENDANG: {
        name: 'Kendang',
        instrument: 'KENDANG',
        type: 'percussion',
        svg_file: 'svg/GK_KENDANG.svg',
        symbolToNoteNames: {
            '0': ['CUNG'],
            '8': ['KA'],
            '9': ['DE'],
            '(': ['TUT'],
            ')': ['KUNG'],
            '*': ['PAK'],
            '0/': ['CUNG'],
            '8/': ['KA'],
            '9/': ['DE'],
            '(/': ['TUT'],
            ')/': ['KUNG'],
            '*/': ['PAK'],
            '0?': ['CUNG'],
            '8?': ['KA'],
            '9?': ['DE'],
            '(?': ['TUT'],
            ')?': ['KUNG'],
            '*?': ['PAK']
        }
    },
    KENDANG_WADON: {
        name: 'Kendang',
        instrument: 'KENDANG',
        type: 'percussion',
        svg_file: 'svg/GK_KENDANG.svg',
        symbolToNoteNames: {
            '0': ['CUNG'],
            '8': ['KA'],
            '9': ['DE'],
            '(': ['TUT'],
            ')': ['KUNG'],
            '*': ['PAK'],
            '0/': ['CUNG'],
            '8/': ['KA'],
            '9/': ['DE'],
            '(/': ['TUT'],
            ')/': ['KUNG'],
            '*/': ['PAK'],
            '0?': ['CUNG'],
            '8?': ['KA'],
            '9?': ['DE'],
            '(?': ['TUT'],
            ')?': ['KUNG'],
            '*?': ['PAK']
        }
    },
    KENDANG_LANANG: {
        name: 'Kendang',
        instrument: 'KENDANG',
        type: 'percussion',
        svg_file: 'svg/GK_KENDANG.svg',
        symbolToNoteNames: {
            '0': ['CUNG'],
            '8': ['KA'],
            '9': ['DE'],
            '(': ['TUT'],
            ')': ['KUNG'],
            '*': ['PAK'],
            '0/': ['CUNG'],
            '8/': ['KA'],
            '9/': ['DE'],
            '(/': ['TUT'],
            ')/': ['KUNG'],
            '*/': ['PAK'],
            '0?': ['CUNG'],
            '8?': ['KA'],
            '9?': ['DE'],
            '(?': ['TUT'],
            ')?': ['KUNG'],
            '*?': ['PAK']
        }
    },
    JEGOGAN: {
        name: 'Jegogan',
        instrument: 'JEGOGAN',
        type: 'daun',
        svg_file: 'svg/GK_JEGOGAN.svg',
        symbolToNoteNames: {
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i/': ['DING1'],
            'o/': ['DONG1'],
            'e/': ['DENG1'],
            'u/': ['DUNG1'],
            'a/': ['DANG1']
        }
    },
    CALUNG: {
        name: 'Calung',
        instrument: 'CALUNG',
        type: 'daun',
        svg_file: 'svg/GK_CALUNG.svg',
        symbolToNoteNames: {
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i/': ['DING1'],
            'o/': ['DONG1'],
            'e/': ['DENG1'],
            'u/': ['DUNG1'],
            'a/': ['DANG1']
        }
    },
    PENYACAH: {
        name: 'Penyacah',
        instrument: 'PENYACAH',
        type: 'daun',
        svg_file: 'svg/GK_PENYACAH.svg',
        symbolToNoteNames: {
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1']
            /*     'u,/': ['DUNG0_ABBR'], 'a,/': ['DANG0_ABBR'], 'i/': ['DING1_ABBR'], 'o/': ['DONG1_ABBR'], 'e/': ['DENG1_ABBR'], 'u/': ['DUNG1_ABBR'], 'a/': ['DANG1_ABBR'] */
        }
    },
    KANTILAN_POLOS: {
        name: 'Kantilan polos',
        instrument: 'KANTILAN',
        type: 'daun',
        svg_file: 'svg/GK_GANGSA.svg',
        symbolToNoteNames: {
            'o,': ['DONG0'],
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o,/': ['DONG0_ABBR'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o,?': ['DONG0_MUTED'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED']
        }
    },
    KANTILAN_SANGSIH: {
        name: 'Kantilan sangsih',
        instrument: 'KANTILAN',
        type: 'daun',
        svg_file: 'svg/GK_GANGSA.svg',
        symbolToNoteNames: {
            'o,': ['DONG0'],
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o,/': ['DONG0_ABBR'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o,?': ['DONG0_MUTED'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED']
        }
    },
    PEMADE_POLOS: {
        name: 'Pemade polos',
        instrument: 'PEMADE',
        type: 'daun',
        svg_file: 'svg/GK_GANGSA.svg',
        symbolToNoteNames: {
            'o,': ['DONG0'],
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o,/': ['DONG0_ABBR'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o,?': ['DONG0_MUTED'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED']
        }
    },
    PEMADE_SANGSIH: {
        name: 'Pemade sangsih',
        instrument: 'PEMADE',
        type: 'daun',
        svg_file: 'svg/GK_GANGSA.svg',
        symbolToNoteNames: {
            'o,': ['DONG0'],
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o,/': ['DONG0_ABBR'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o,?': ['DONG0_MUTED'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED']
        }
    },
    UGAL: {
        name: 'Ugal',
        instrument: 'UGAL',
        type: 'daun',
        svg_file: 'svg/GK_UGAL.svg',
        symbolToNoteNames: {
            'o,': ['DONG0'],
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o,/': ['DONG0_ABBR'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o,?': ['DONG0_MUTED'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED']
        }
    },
    TROMPONG: {
        name: 'Trompong',
        instrument: 'TROMPONG',
        type: 'daun',
        svg_file: 'svg/GK_UGAL.svg',
        symbolToNoteNames: {
            'a,': ['DANG0'],
            'i,': ['DING0'],
            'o,': ['DONG0'],
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            a: ['DANG1'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            'a,/': ['DANG0_ABBR'],
            'i,/': ['DING0_ABBR'],
            'o,/': ['DONG0_ABBR'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a,?': ['DANG0_MUTED'],
            'i,?': ['DING0_MUTED'],
            'o,?': ['DONG0_MUTED'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED']
        }
    },
    GENDER_RAMBAT: {
        name: 'Gender rambat',
        instrument: 'GENDER_RAMBAT',
        type: 'daun',
        svg_file: '',
        symbolToNoteNames: {
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED']
        }
    },
    REYONG_1: {
        name: 'Reyong 1',
        instrument: 'REYONG',
        type: 'chimes',
        svg_file: 'svg/GK_REYONG.svg',
        symbolToNoteNames: {
            'e,': ['DENG0'],
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            'e,/': ['DENG0_ABBR'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'e,?': ['DENG0_MUTED'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            t: ['DENG0', 'DING1'],
            't?': ['DENG0_MUTED', 'DING1_MUTED'],
            b: ['DENG0', 'DANG0'],
            'b/': ['DENG0_ABBR', 'DANG0_ABBR'],
            'b?': ['DENG0_MUTED', 'DANG0_MUTED'],
            x: ['XDUNG0'],
            'x/': ['XDUNG0_ABBR'],
            'x?': ['XDUNG0_MUTED']
        }
    },
    REYONG_2: {
        name: 'Reyong 2',
        instrument: 'REYONG',
        type: 'chimes',
        svg_file: 'svg/GK_REYONG.svg',
        symbolToNoteNames: {
            'u,': ['DUNG0'],
            'a,': ['DANG0'],
            i: ['DING1'],
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'u,/': ['DUNG0_ABBR'],
            'a,/': ['DANG0_ABBR'],
            'i/': ['DING1_ABBR'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'u,?': ['DUNG0_MUTED'],
            'a,?': ['DANG0_MUTED'],
            'i?': ['DING1_MUTED'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            b: ['DING1', 'DENG1'],
            'b/': ['DING1_ABBR', 'DENG1_ABBR'],
            'b?': ['DING1_MUTED', 'DENG1_MUTED'],
            x: ['XDONG1'],
            'x/': ['XDONG1_ABBR'],
            'x?': ['XDONG1_MUTED']
        }
    },
    REYONG_3: {
        name: 'Reyong 3',
        instrument: 'REYONG',
        type: 'chimes',
        svg_file: 'svg/GK_REYONG.svg',
        symbolToNoteNames: {
            o: ['DONG1'],
            e: ['DENG1'],
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o<': ['DONG2'],
            'e<': ['DENG2'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o</': ['DONG2_ABBR'],
            'e</': ['DENG2_ABBR'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED'],
            'o<?': ['DONG2_MUTED'],
            'e<?': ['DENG2_MUTED'],
            b: ['DUNG1', 'DING2'],
            'b/': ['DUNG1_ABBR', 'DING2_ABBR'],
            'b?': ['DUNG1_MUTED', 'DING2_MUTED'],
            x: ['XDANG1'],
            'x/': ['XDANG1_ABBR'],
            'x?': ['XDANG1_MUTED']
        }
    },
    REYONG_4: {
        name: 'Reyong 4',
        instrument: 'REYONG',
        type: 'chimes',
        svg_file: 'svg/GK_REYONG.svg',
        symbolToNoteNames: {
            u: ['DUNG1'],
            a: ['DANG1'],
            'i<': ['DING2'],
            'o<': ['DONG2'],
            'e<': ['DENG2'],
            'u<': ['DUNG2'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'i</': ['DING2_ABBR'],
            'o</': ['DONG2_ABBR'],
            'e</': ['DENG2_ABBR'],
            'u</': ['DUNG2_ABBR'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            'i<?': ['DING2_MUTED'],
            'o<?': ['DONG2_MUTED'],
            'e<?': ['DENG2_MUTED'],
            'u<?': ['DUNG2_MUTED'],
            b: ['DONG2', 'DUNG2'],
            'b/': ['DONG2_ABBR', 'DUNG2_ABBR'],
            'b?': ['DONG2_MUTED', 'DUNG2_MUTED'],
            x: ['XDENG2'],
            'x/': ['XDENG2_ABBR'],
            'x?': ['XDENG2_MUTED']
        }
    },
    CENGCENG_P: {
        name: 'Cengceng polos',
        instrument: 'CENGCENG_KOPYAK',
        type: 'percussion',
        svg_file: '',
        symbolToNoteNames: { x: ['X_OPEN'], 'x?': ['X_MUTED'] }
    },
    CENGCENG_S: {
        name: 'Cengceng sangsih',
        instrument: 'CENGCENG_KOPYAK',
        type: 'percussion',
        svg_file: '',
        symbolToNoteNames: { x: ['X_OPEN'], 'x?': ['X_MUTED'] }
    },
    REYONGB_1: {
        name: 'Reyong 1',
        instrument: 'REYONGB',
        type: 'chimes',
        svg_file: '',
        symbolToNoteNames: {
            o: ['DONG1'],
            e: ['DENG1'],
            'o/': ['DONG1_ABBR'],
            'e/': ['DENG1_ABBR'],
            'o?': ['DONG1_MUTED'],
            'e?': ['DENG1_MUTED'],
            b: ['DONG1', 'DENG1'],
            'b/': ['DONG1_ABBR', 'DENG1_ABBR'],
            'b?': ['DONG1_MUTED', 'DENG1_MUTED'],
            x: ['XDONG1'],
            'x/': ['XDONG1_ABBR'],
            'x?': ['XDONG1_MUTED']
        }
    },
    REYONGB_2: {
        name: 'Reyong 2',
        instrument: 'REYONGB',
        type: 'chimes',
        svg_file: '',
        symbolToNoteNames: {
            u: ['DUNG1'],
            a: ['DANG1'],
            'u/': ['DUNG1_ABBR'],
            'a/': ['DANG1_ABBR'],
            'u?': ['DUNG1_MUTED'],
            'a?': ['DANG1_MUTED'],
            b: ['DUNG1', 'DANG1'],
            'b/': ['DUNG1_ABBR', 'DANG1_ABBR'],
            'b?': ['DUNG1_MUTED', 'DANG1_MUTED'],
            x: ['XDUNG1'],
            'x/': ['XDUNG1_ABBR'],
            'x?': ['XDUNG1_MUTED']
        }
    },
    TAWATAWA: {
        name: 'Tawa tawa',
        instrument: 'TAWATAWA',
        type: 'percussion',
        svg_file: '',
        symbolToNoteNames: { x: ['X'] }
    },
    PONGGANG: {
        name: 'Ponggang',
        instrument: 'PONGGANG',
        type: 'chimes',
        svg_file: '',
        symbolToNoteNames: { u: ['DUNG1'], a: ['DANG1'] }
    }
}
