// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$OOQOPOOO]OPO'#C_OOOO'#Ck'#CkObOPO'#C^QmOPOOOrOPO,58yOOOO-E6i-E6iOwOPO'#CdO|OPO'#CcOOOO'#Cl'#ClQmOPOOOOOO1G.e1G.eO!ROPO,59OO!WOPO'#CiOOOO'#Cm'#CmO!]OPO,58}OOOO-E6j-E6jO!hOPO1G.jO!mOPO,59TOOOO-E6k-E6kO!rOPO7+$UOOOO1G.o1G.oOOOO<<Gp<<Gp",
  stateData: "!w~OSPOXQPbQP~OTTO~OSPOXQXbQX~OXVO~OUZO~OU[O~OS]O~OYaO~OTbO~OS]OXVabVa~OZdO~O^eO~O[fO~O",
  goto: "!YbPPcfPPPjnPPPPrPv|!SRSOTQORTXSYTWSYT^W_QRORURQYSR`YQ_WRc_",
  nodeNames: "⚠ File Metadata MetadataValue Name Space String System SystemHeader LBracket Comma Number RBracket SectionData Code",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%U~RcX^!^pq!^rs#R|}#p!Q![#u!c!}#}!}#O$]#P#Q$b#R#S#}#S#T$g#T#o#}#y#z!^$f$g!^#BY#BZ!^$IS$I_!^$I|$JO!^$JT$JU!^$KV$KW!^&FU&FV!^~!cYT~X^!^pq!^#y#z!^$f$g!^#BY#BZ!^$IS$I_!^$I|$JO!^$JT$JU!^$KV$KW!^&FU&FV!^~#UTOr#Rrs#es;'S#R;'S;=`#j<%lO#R~#jOU~~#mP;=`<%l#R~#uOY~~#zPZ~!Q![#u~$SRS~!c!}#}#R#S#}#T#o#}~$bOX~~$gO[~~$jTO#S$g#S#T$y#T;'S$g;'S;=`%O<%lO$g~%OO^~~%RP;=`<%l$g",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
