// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  Metadata = 2,
  MetadataValue = 3,
  Name = 4,
  Space = 5,
  String = 6,
  System = 7,
  SystemHeader = 8,
  LBracket = 9,
  Comma = 10,
  Number = 11,
  RBracket = 12,
  SectionData = 13,
  Code = 14
