import type { Note } from "../models/types"

export const dimRateNonFocusedInstruments = 0.2 // Fraction to which the volume of instruments other than the focus should be reduced
export const BaseNote: "1n" | "2n" | "4n" | "8n" | "16n" | "32n" = "16n"
export const SOUNDS_FOLDER = 'sounds/'
export const alwaysFocusPositions = ["KEMPLI", "GONGS"]

// Check if the set of sample files is complete
export const doSanityCheck = false

export const NOTES = ['C1', 'C#1', 'D1', 'D#1', 'E1', 'F1', 'F#1', 'G1', 'G#1', 'A1', 'A#1', 'B1', 'C2', 'C#2', 'D2', 'D#2', 'E2', 'F2', 'F#2', 'G2', 'G#2', 'A2', 'A#2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A#3', 'B3']

// Typing of tone and muting
// See https://stackoverflow.com/questions/54607961/how-to-define-a-type-based-on-values-of-an-array
const _tones_ = ['DING', 'DONG', 'DENG', 'DUNG', 'DANG', 'GIR', 'PUR', 'TONG', 'X', 'X', 'KA', 'PAK', 'DE', 'TUT', 'CUNG', 'KUNG'] as const
export type ToneType = typeof _tones_[number]; // 'DING' | 'DONG' | 'DENG' | ...
const _strokes_ = ['KNOB', 'RIM'] as const
export type StrokeType = typeof _strokes_[number];
const _mutings_ = ['OPEN', 'ABBREVIATED', 'MUTED'] as const
export type MutingType = typeof _mutings_[number];

export type InstrumentConfig = {
    name: string
    positions: string[]
}

export type PositionConfig = {
    //`notes` contains a list of single notes or multiple notes that are played simultaneously.
    // The string values are 'shorthand' codes that uniquely define a sample (see const noteConfigs).
    name: string
    type: string
    svg_file: string,
    sampletemplate: string
    volume: number
    symbolToNoteNames: { [symbol: string]: string[] }
}

// The following characters should be ignored when sending a note to a Sampler.
// TODO This is a temporary solution to avoid having to double the length of each
// alphabet for these rarely used modifiers.
export const ignoreChars: string[] = ["_", "="]  // half and quarter base note duration.

// Translates shorthand codes used in instrumentConfigs to Note records.
// The stroke is used for the animation.
export const noteConfigs: Record<string, Record<string, Note>> = {
    'percussion': {
        // GONGS
        'GIR': { tone: 'GIR', octave: null, stroke: null, muting: 'OPEN' },
        'PUR': { tone: 'PUR', octave: null, stroke: null, muting: 'OPEN' },
        'TONG': { tone: 'TONG', octave: null, stroke: null, muting: 'OPEN' },
        // KEMPLI
        'X_OPEN': { tone: 'X', octave: null, stroke: 'KNOB', muting: 'OPEN' },
        'X_MUTED': { tone: 'X', octave: null, stroke: 'KNOB', muting: 'MUTED' },
        // KENDANG
        'KA': { tone: 'KA', octave: null, stroke: null, muting: 'OPEN' },
        'PAK': { tone: 'PAK', octave: null, stroke: null, muting: 'OPEN' },
        'DE': { tone: 'DE', octave: null, stroke: null, muting: 'OPEN' },
        'TUT': { tone: 'TUT', octave: null, stroke: null, muting: 'OPEN' },
        'CUNG': { tone: 'CUNG', octave: null, stroke: null, muting: 'OPEN' },
        'KUNG': { tone: 'KUNG', octave: null, stroke: null, muting: 'OPEN' },
    },
    'daun': {
        'DONG0': { tone: 'DONG', octave: 0, stroke: null, muting: 'OPEN' },
        'DENG0': { tone: 'DENG', octave: 0, stroke: null, muting: 'OPEN' },
        'DUNG0': { tone: 'DUNG', octave: 0, stroke: null, muting: 'OPEN' },
        'DANG0': { tone: 'DANG', octave: 0, stroke: null, muting: 'OPEN' },
        'DING1': { tone: 'DING', octave: 1, stroke: null, muting: 'OPEN' },
        'DONG1': { tone: 'DONG', octave: 1, stroke: null, muting: 'OPEN' },
        'DENG1': { tone: 'DENG', octave: 1, stroke: null, muting: 'OPEN' },
        'DUNG1': { tone: 'DUNG', octave: 1, stroke: null, muting: 'OPEN' },
        'DANG1': { tone: 'DANG', octave: 1, stroke: null, muting: 'OPEN' },
        'DING2': { tone: 'DING', octave: 2, stroke: null, muting: 'OPEN' },
        'DONG0_ABBR': { tone: 'DONG', octave: 0, stroke: null, muting: 'ABBREVIATED' },
        'DENG0_ABBR': { tone: 'DENG', octave: 0, stroke: null, muting: 'ABBREVIATED' },
        'DUNG0_ABBR': { tone: 'DUNG', octave: 0, stroke: null, muting: 'ABBREVIATED' },
        'DANG0_ABBR': { tone: 'DANG', octave: 0, stroke: null, muting: 'ABBREVIATED' },
        'DING1_ABBR': { tone: 'DING', octave: 1, stroke: null, muting: 'ABBREVIATED' },
        'DONG1_ABBR': { tone: 'DONG', octave: 1, stroke: null, muting: 'ABBREVIATED' },
        'DENG1_ABBR': { tone: 'DENG', octave: 1, stroke: null, muting: 'ABBREVIATED' },
        'DUNG1_ABBR': { tone: 'DUNG', octave: 1, stroke: null, muting: 'ABBREVIATED' },
        'DANG1_ABBR': { tone: 'DANG', octave: 1, stroke: null, muting: 'ABBREVIATED' },
        'DING2_ABBR': { tone: 'DING', octave: 2, stroke: null, muting: 'ABBREVIATED' },
        'DONG0_MUTED': { tone: 'DONG', octave: 0, stroke: null, muting: 'MUTED' },
        'DENG0_MUTED': { tone: 'DENG', octave: 0, stroke: null, muting: 'MUTED' },
        'DUNG0_MUTED': { tone: 'DUNG', octave: 0, stroke: null, muting: 'MUTED' },
        'DANG0_MUTED': { tone: 'DANG', octave: 0, stroke: null, muting: 'MUTED' },
        'DING1_MUTED': { tone: 'DING', octave: 1, stroke: null, muting: 'MUTED' },
        'DONG1_MUTED': { tone: 'DONG', octave: 1, stroke: null, muting: 'MUTED' },
        'DENG1_MUTED': { tone: 'DENG', octave: 1, stroke: null, muting: 'MUTED' },
        'DUNG1_MUTED': { tone: 'DUNG', octave: 1, stroke: null, muting: 'MUTED' },
        'DANG1_MUTED': { tone: 'DANG', octave: 1, stroke: null, muting: 'MUTED' },
        'DING2_MUTED': { tone: 'DING', octave: 2, stroke: null, muting: 'MUTED' },
    },
    "chimes": {
        // REYONG SPECIFIC
        'DENG0': { tone: 'DENG', octave: 0, stroke: 'KNOB', muting: 'OPEN' },
        'DUNG0': { tone: 'DUNG', octave: 0, stroke: 'KNOB', muting: 'OPEN' },
        'DANG0': { tone: 'DANG', octave: 0, stroke: 'KNOB', muting: 'OPEN' },
        'DING1': { tone: 'DING', octave: 1, stroke: 'KNOB', muting: 'OPEN' },
        'DONG1': { tone: 'DONG', octave: 1, stroke: 'KNOB', muting: 'OPEN' },
        'DENG1': { tone: 'DENG', octave: 1, stroke: 'KNOB', muting: 'OPEN' },
        'DUNG1': { tone: 'DUNG', octave: 1, stroke: 'KNOB', muting: 'OPEN' },
        'DANG1': { tone: 'DANG', octave: 1, stroke: 'KNOB', muting: 'OPEN' },
        'DING2': { tone: 'DING', octave: 2, stroke: 'KNOB', muting: 'OPEN' },
        'DONG2': { tone: 'DONG', octave: 2, stroke: 'KNOB', muting: 'OPEN' },
        'DENG2': { tone: 'DENG', octave: 2, stroke: 'KNOB', muting: 'OPEN' },
        'DUNG2': { tone: 'DUNG', octave: 2, stroke: 'KNOB', muting: 'OPEN' },
        'DENG0_ABBR': { tone: 'DENG', octave: 0, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DUNG0_ABBR': { tone: 'DUNG', octave: 0, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DANG0_ABBR': { tone: 'DANG', octave: 0, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DING1_ABBR': { tone: 'DING', octave: 1, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DONG1_ABBR': { tone: 'DONG', octave: 1, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DENG1_ABBR': { tone: 'DENG', octave: 1, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DUNG1_ABBR': { tone: 'DUNG', octave: 1, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DANG1_ABBR': { tone: 'DANG', octave: 1, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DING2_ABBR': { tone: 'DING', octave: 2, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DONG2_ABBR': { tone: 'DONG', octave: 2, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DENG2_ABBR': { tone: 'DENG', octave: 2, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DUNG2_ABBR': { tone: 'DUNG', octave: 2, stroke: 'KNOB', muting: 'ABBREVIATED' },
        'DENG0_MUTED': { tone: 'DENG', octave: 0, stroke: 'KNOB', muting: 'MUTED' },
        'DUNG0_MUTED': { tone: 'DUNG', octave: 0, stroke: 'KNOB', muting: 'MUTED' },
        'DANG0_MUTED': { tone: 'DANG', octave: 0, stroke: 'KNOB', muting: 'MUTED' },
        'DING1_MUTED': { tone: 'DING', octave: 1, stroke: 'KNOB', muting: 'MUTED' },
        'DONG1_MUTED': { tone: 'DONG', octave: 1, stroke: 'KNOB', muting: 'MUTED' },
        'DENG1_MUTED': { tone: 'DENG', octave: 1, stroke: 'KNOB', muting: 'MUTED' },
        'DUNG1_MUTED': { tone: 'DUNG', octave: 1, stroke: 'KNOB', muting: 'MUTED' },
        'DANG1_MUTED': { tone: 'DANG', octave: 1, stroke: 'KNOB', muting: 'MUTED' },
        'DING2_MUTED': { tone: 'DING', octave: 2, stroke: 'KNOB', muting: 'MUTED' },
        'DONG2_MUTED': { tone: 'DONG', octave: 2, stroke: 'KNOB', muting: 'MUTED' },
        'DENG2_MUTED': { tone: 'DENG', octave: 2, stroke: 'KNOB', muting: 'MUTED' },
        'DUNG2_MUTED': { tone: 'DUNG', octave: 2, stroke: 'KNOB', muting: 'MUTED' },
        'XDUNG0': { tone: 'DUNG', octave: 0, stroke: 'RIM', muting: 'OPEN' },
        'XDONG1': { tone: 'DONG', octave: 1, stroke: 'RIM', muting: 'OPEN' },
        'XDANG1': { tone: 'DANG', octave: 1, stroke: 'RIM', muting: 'OPEN' },
        'XDENG2': { tone: 'DENG', octave: 2, stroke: 'RIM', muting: 'OPEN' },
        'XDUNG0_MUTED': { tone: 'DUNG', octave: 0, stroke: 'RIM', muting: 'MUTED' },
        'XDONG1_MUTED': { tone: 'DONG', octave: 1, stroke: 'RIM', muting: 'MUTED' },
        'XDANG1_MUTED': { tone: 'DANG', octave: 1, stroke: 'RIM', muting: 'MUTED' },
        'XDENG2_MUTED': { tone: 'DENG', octave: 2, stroke: 'RIM', muting: 'MUTED' },
    }
}

export const instrumentConfigs: Record<string, InstrumentConfig> = {
    GONGS: { name: "Gongs", positions: ["GONGS"] },
    KEMPLI: { name: "Kempli", positions: ["KEMPLI"], },
    CENGCENG: { name: "Cengceng", positions: ["CENGCENG"], },
    KENDANG: { name: "Kendang", positions: ["KENDANG"], },
    JEGOGAN: { name: "Jegogan", positions: ["JEGOGAN"], },
    CALUNG: { name: "Calung", positions: ["CALUNG"], },
    PENYACAH: { name: "Penyacah", positions: ["PENYACAH"], },
    PEMADE: { name: "Pemade", positions: ["PEMADE_POLOS", "PEMADE_SANGSIH"], },
    KANTILAN: { name: "Kantilan", positions: ["KANTILAN_POLOS", "KANTILAN_SANGSIH"], },
    UGAL: { name: "Ugal", positions: ["UGAL"], },
    REYONG: { name: "Reyong", positions: ["REYONG_1", "REYONG_2", "REYONG_3", "REYONG_4"], },
}



export const editorSortingOrder = ["UGAL", "PEMADE_POLOS", "PEMADE_SANGSIH", "KANTILAN_POLOS", "KANTILAN_SANGSIH", "REYONG_1", "REYONG_2", "REYONG_3", "REYONG_4", "PENYACAH", "CALUNG", "JEGOGAN", "GONGS", "CENGCENG", "KENDANG", "KEMPLI"]

export const positionConfigs: Record<string, PositionConfig> = {
    GONGS: {
        name: "Gongs",
        type: "percussion",
        volume: -5,
        svg_file: "svg/GK_GONGS.svg",
        sampletemplate: "GK_GONGS_{note}.mp3",
        symbolToNoteNames: {
            "G": ["GIR"],
            "P": ["PUR"],
            "T": ["TONG"]
        }
    },
    KEMPLI: {
        name: "Kempli",
        type: "percussion",
        volume: -5,
        svg_file: "",
        sampletemplate: "GK_KEMPLI_{note}.mp3",
        symbolToNoteNames: { "x?": ["X_MUTED"] }
    },
    CENGCENG: {
        name: "Cengceng",
        type: "percussion",
        volume: -14,
        svg_file: "",
        sampletemplate: "GK_CENGCENG_{note}.mp3",
        symbolToNoteNames: {
            "x": ["X_OPEN"],
            "x?": ["X_MUTED"]
        }
    },
    KENDANG: {
        name: "Kendang",
        type: "percussion",
        volume: 0,
        svg_file: "svg/GK_KENDANG.svg",
        sampletemplate: "GK_KENDANG_{note}.wav",
        symbolToNoteNames: {
            "0": ["CUNG"],
            "8": ["KA"],
            "9": ["DE"],
            "(": ["TUT"],
            ")": ["KUNG"],
            "*": ["PAK"]
        }
    },
    JEGOGAN: {
        name: "Jegogan",
        type: "daun",
        volume: -5,
        svg_file: "svg/GK_JEGOGAN.svg",
        sampletemplate: "GK_JEGOGAN_{note}.mp3",
        symbolToNoteNames: {
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i/": ["DING1"],
            "o/": ["DONG1"],
            "e/": ["DENG1"],
            "u/": ["DUNG1"],
            "a/": ["DANG1"]
        }
    },
    CALUNG: {
        name: "Calung",
        type: "daun",
        volume: -5,
        svg_file: "svg/GK_CALUNG.svg",
        sampletemplate: "GK_CALUNG_{note}.mp3",
        symbolToNoteNames: {
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i/": ["DING1"],
            "o/": ["DONG1"],
            "e/": ["DENG1"],
            "u/": ["DUNG1"],
            "a/": ["DANG1"]
        }
    },
    PENYACAH: {
        name: "Penyacah",
        type: "daun",
        volume: -15,
        svg_file: "svg/GK_PENYACAH.svg",
        sampletemplate: "GK_PENYACAH_{note}.mp3",
        symbolToNoteNames: {
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "u,/": ["DUNG0"],
            "a,/": ["DANG0"],
            "i/": ["DING1"],
            "o/": ["DONG1"],
            "e/": ["DENG1"],
            "u/": ["DUNG1"],
            "a/": ["DANG1"]
        }
    },
    KANTILAN_POLOS: {
        name: "Kantilan polos",
        type: "daun",
        volume: -14,
        svg_file: "svg/GK_GANGSA.svg",
        sampletemplate: "GK_KANTILAN_{note}.mp3",
        symbolToNoteNames: {
            "o,": ["DONG0"],
            "e,": ["DENG0"],
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i<": ["DING2"],
            "o,/": ["DONG0_ABBR"],
            "e,/": ["DENG0_ABBR"],
            "u,/": ["DUNG0_ABBR"],
            "a,/": ["DANG0_ABBR"],
            "i/": ["DING1_ABBR"],
            "o/": ["DONG1_ABBR"],
            "e/": ["DENG1_ABBR"],
            "u/": ["DUNG1_ABBR"],
            "a/": ["DANG1_ABBR"],
            "i</": ["DING2_ABBR"],
            "o,?": ["DONG0_MUTED"],
            "e,?": ["DENG0_MUTED"],
            "u,?": ["DUNG0_MUTED"],
            "a,?": ["DANG0_MUTED"],
            "i?": ["DING1_MUTED"],
            "o?": ["DONG1_MUTED"],
            "e?": ["DENG1_MUTED"],
            "u?": ["DUNG1_MUTED"],
            "a?": ["DANG1_MUTED"],
            "i<?": ["DING2_MUTED"]
        }
    },
    KANTILAN_SANGSIH: {
        name: "Kantilan sangsih",
        type: "daun",
        volume: -14,
        svg_file: "svg/GK_GANGSA.svg",
        sampletemplate: "GK_KANTILAN_{note}.mp3",
        symbolToNoteNames: {
            "o,": ["DONG0"],
            "e,": ["DENG0"],
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i<": ["DING2"],
            "o,/": ["DONG0_ABBR"],
            "e,/": ["DENG0_ABBR"],
            "u,/": ["DUNG0_ABBR"],
            "a,/": ["DANG0_ABBR"],
            "i/": ["DING1_ABBR"],
            "o/": ["DONG1_ABBR"],
            "e/": ["DENG1_ABBR"],
            "u/": ["DUNG1_ABBR"],
            "a/": ["DANG1_ABBR"],
            "i</": ["DING2_ABBR"],
            "o,?": ["DONG0_MUTED"],
            "e,?": ["DENG0_MUTED"],
            "u,?": ["DUNG0_MUTED"],
            "a,?": ["DANG0_MUTED"],
            "i?": ["DING1_MUTED"],
            "o?": ["DONG1_MUTED"],
            "e?": ["DENG1_MUTED"],
            "u?": ["DUNG1_MUTED"],
            "a?": ["DANG1_MUTED"],
            "i<?": ["DING2_MUTED"]
        }
    },
    PEMADE_POLOS: {
        name: "Pemade polos",
        type: "daun",
        volume: -14,
        svg_file: "svg/GK_GANGSA.svg",
        sampletemplate: "GK_PEMADE_{note}.mp3",
        symbolToNoteNames: {
            "o,": ["DONG0"],
            "e,": ["DENG0"],
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i<": ["DING2"],
            "o,/": ["DONG0_ABBR"],
            "e,/": ["DENG0_ABBR"],
            "u,/": ["DUNG0_ABBR"],
            "a,/": ["DANG0_ABBR"],
            "i/": ["DING1_ABBR"],
            "o/": ["DONG1_ABBR"],
            "e/": ["DENG1_ABBR"],
            "u/": ["DUNG1_ABBR"],
            "a/": ["DANG1_ABBR"],
            "i</": ["DING2_ABBR"],
            "o,?": ["DONG0_MUTED"],
            "e,?": ["DENG0_MUTED"],
            "u,?": ["DUNG0_MUTED"],
            "a,?": ["DANG0_MUTED"],
            "i?": ["DING1_MUTED"],
            "o?": ["DONG1_MUTED"],
            "e?": ["DENG1_MUTED"],
            "u?": ["DUNG1_MUTED"],
            "a?": ["DANG1_MUTED"],
            "i<?": ["DING2_MUTED"]
        }
    },
    PEMADE_SANGSIH: {
        name: "Pemade sangsih",
        type: "daun",
        volume: -14,
        svg_file: "svg/GK_GANGSA.svg",
        sampletemplate: "GK_PEMADE_{note}.mp3",
        symbolToNoteNames: {
            "o,": ["DONG0"],
            "e,": ["DENG0"],
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i<": ["DING2"],
            "o,/": ["DONG0_ABBR"],
            "e,/": ["DENG0_ABBR"],
            "u,/": ["DUNG0_ABBR"],
            "a,/": ["DANG0_ABBR"],
            "i/": ["DING1_ABBR"],
            "o/": ["DONG1_ABBR"],
            "e/": ["DENG1_ABBR"],
            "u/": ["DUNG1_ABBR"],
            "a/": ["DANG1_ABBR"],
            "i</": ["DING2_ABBR"],
            "o,?": ["DONG0_MUTED"],
            "e,?": ["DENG0_MUTED"],
            "u,?": ["DUNG0_MUTED"],
            "a,?": ["DANG0_MUTED"],
            "i?": ["DING1_MUTED"],
            "o?": ["DONG1_MUTED"],
            "e?": ["DENG1_MUTED"],
            "u?": ["DUNG1_MUTED"],
            "a?": ["DANG1_MUTED"],
            "i<?": ["DING2_MUTED"]
        }
    },
    UGAL: {
        name: "Ugal",
        type: "daun",
        volume: -14,
        svg_file: "svg/GK_UGAL.svg",
        sampletemplate: "GK_UGAL_{note}.mp3",
        symbolToNoteNames: {
            "o,": ["DONG0"],
            "e,": ["DENG0"],
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i<": ["DING2"],
            "o,/": ["DONG0_ABBR"],
            "e,/": ["DENG0_ABBR"],
            "u,/": ["DUNG0_ABBR"],
            "a,/": ["DANG0_ABBR"],
            "i/": ["DING1_ABBR"],
            "o/": ["DONG1_ABBR"],
            "e/": ["DENG1_ABBR"],
            "u/": ["DUNG1_ABBR"],
            "a/": ["DANG1_ABBR"],
            "i</": ["DING2_ABBR"],
            "o,?": ["DONG0_MUTED"],
            "e,?": ["DENG0_MUTED"],
            "u,?": ["DUNG0_MUTED"],
            "a,?": ["DANG0_MUTED"],
            "i?": ["DING1_MUTED"],
            "o?": ["DONG1_MUTED"],
            "e?": ["DENG1_MUTED"],
            "u?": ["DUNG1_MUTED"],
            "a?": ["DANG1_MUTED"],
            "i<?": ["DING2_MUTED"]
        }
    },
    REYONG_1: {
        name: "Reyong 1",
        type: "chimes",
        volume: -14,
        svg_file: "svg/GK_REYONG.svg",
        sampletemplate: "GK_REYONG_{note}.mp3",
        symbolToNoteNames: {
            "e,": ["DENG0"],
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "t": ["DENG0", "DING1"],
            "t?": ["DENG0_MUTED", "DING1_MUTED"],
            "b": ["DENG0", "DANG0"],
            "b/": ["DENG0_ABBR", "DANG0_ABBR"],
            "b?": ["DENG0_MUTED", "DANG0_MUTED"],
            "x": ["XDUNG0"],
            "x/": ["XDUNG0_MUTED"]
        }
    },
    REYONG_2: {
        name: "Reyong 2",
        type: "chimes",
        volume: -14,
        svg_file: "svg/GK_REYONG.svg",
        sampletemplate: "GK_REYONG_{note}.mp3",
        symbolToNoteNames: {
            "u,": ["DUNG0"],
            "a,": ["DANG0"],
            "i": ["DING1"],
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "b": ["DING1", "DENG1"],
            "b/": ["DING1_ABBR", "DENG1_ABBR"],
            "b?": ["DING1_MUTED", "DENG1_MUTED"],
            "x": ["XDONG1"],
            "x/": ["XDONG1_MUTED"]
        }
    },
    REYONG_3: {
        name: "Reyong 3",
        type: "chimes",
        volume: -14,
        svg_file: "svg/GK_REYONG.svg",
        sampletemplate: "GK_REYONG_{note}.mp3",
        symbolToNoteNames: {
            "o": ["DONG1"],
            "e": ["DENG1"],
            "u": ["DUNG1"],
            "a": ["DANG1"],
            "i<": ["DING2"],
            "o<": ["DONG2"],
            "e<": ["DENG2"],
            "b": ["DUNG1", "DING2"],
            "b/": ["DUNG1_ABBR", "DING2_ABBR"],
            "b?": ["DUNG1_MUTED", "DING2_MUTED"],
            "x": ["XDANG1"],
            "x/": ["XDANG1_MUTED"]
        }
    },
    REYONG_4: {
        name: "Reyong 4",
        type: "chimes",
        volume: -14,
        svg_file: "svg/GK_REYONG.svg",
        sampletemplate: "GK_REYONG_{note}.mp3",
        symbolToNoteNames: {
            "u": ["DUNG1"],
            "a,": ["DANG1"],
            "i<": ["DING2"],
            "o<": ["DONG2"],
            "e<": ["DENG2"],
            "u<": ["DUNG2"],
            "b": ["DONG2", "DUNG2"],
            "b/": ["DONG2_ABBR", "DUNG2_ABBR"],
            "b?": ["DONG2_MUTED", "DUNG2_MUTED"],
            "x": ["XDENG2"],
            "x/": ["XDENG2_MUTED"]
        }
    }
}


export type InstrumentAnimationInfo = { group: string, label: string, svg_file: string }

export type AnimationConfig = {
    instrumentation: { [name: string]: InstrumentAnimationInfo[] }
    highlight: { [muting: string]: string[] }
}

export const focusOptions = {
    // value: [positions]
    GONGS: ["GONGS"],
    KENDANG: ["KENDANG"],
    JEGOGAN: ["JEGOGAN"],
    CALUNG: ["CALUNG"],
    PENYACAH: ["PENYACAH"],
    KANTILAN: ["KANTILAN_POLOS", "KANTILAN_SANGSIH"],
    "- KANTILAN_POLOS": ["KANTILAN_POLOS"],
    "- KANTILAN_SANGSIH": ["KANTILAN_SANGSIH"],
    PEMADE: ["PEMADE_POLOS", "PEMADE_SANGSIH"],
    "- PEMADE_POLOS": ["PEMADE_POLOS"],
    "- PEMADE_SANGSIH": ["PEMADE_SANGSIH"],
    UGAL: ["UGAL"],
    REYONG: ["REYONG_1", "REYONG_2", "REYONG_3", "REYONG_4"],
    "- REYONG_1": ["REYONG_1"],
    "- REYONG_2": ["REYONG_2"],
    "- REYONG_3": ["REYONG_3"],
    "- REYONG_4": ["REYONG_4"],
}

export const animationConfig: Record<string, Partial<Record<MutingType | ToneType, string[]>>> = {
    // Highlight determines the highlight color.
    // Highlight keys can be a pitch or a muting type.
    // In case of a multiple match the pitch takes priority.
    highlight: {
        OPEN: ["l-green", "l-blue", "l-cyan", "l-magenta"],
        ABBREVIATED: ["m-green", "m-blue", "m-cyan", "m-magenta"],
        MUTED: ["d-green", "d-blue", "d-cyan", "d-magenta"],
        KA: ["green"],
        PAK: ["green"],
        DE: ["blue"],
        TUT: ["blue"],
        CUNG: ["purple"],
        KUNG: ["purple"],
    }
}

export const colorRGB: Record<string, number[]> = {
    "l-green": [0, 255, 0],
    "m-green": [0, 160, 0],
    "d-green": [0, 80, 0],
    "l-blue": [0, 0, 255],
    "m-blue": [0, 0, 160],
    "d-blue": [0, 0, 80],
    "l-cyan": [0, 255, 255],
    "m-cyan": [0, 160, 160],
    "d-cyan": [0, 80, 80],
    "l-magenta": [255, 0, 255],
    "m-magenta": [160, 0, 160],
    "d-magenta": [80, 0, 80],
    "aliceblue": [240, 248, 255],
    "antiquewhite": [250, 235, 215],
    "aqua": [0, 255, 255],
    "aquamarine": [127, 255, 212],
    "azure": [240, 255, 255],
    "beige": [245, 245, 220],
    "bisque": [255, 228, 196],
    "black": [0, 0, 0],
    "blanchedalmond": [255, 235, 205],
    "blue": [0, 0, 255],
    "blueviolet": [138, 43, 226],
    "brown": [165, 42, 42],
    "burlywood": [222, 184, 135],
    "cadetblue": [95, 158, 160],
    "chartreuse": [127, 255, 0],
    "chocolate": [210, 105, 30],
    "coral": [255, 127, 80],
    "cornflowerblue": [100, 149, 237],
    "cornsilk": [255, 248, 220],
    "crimson": [220, 20, 60],
    "cyan": [0, 255, 255],
    "darkblue": [0, 0, 139],
    "darkcyan": [0, 139, 139],
    "darkgoldenrod": [184, 134, 11],
    "darkgray": [169, 169, 169],
    "darkgreen": [0, 100, 0],
    "darkgrey": [169, 169, 169],
    "darkkhaki": [189, 183, 107],
    "darkmagenta": [139, 0, 139],
    "darkolivegreen": [85, 107, 47],
    "darkorange": [255, 140, 0],
    "darkorchid": [153, 50, 204],
    "darkred": [139, 0, 0],
    "darksalmon": [233, 150, 122],
    "darkseagreen": [143, 188, 143],
    "darkslateblue": [72, 61, 139],
    "darkslategray": [47, 79, 79],
    "darkslategrey": [47, 79, 79],
    "darkturquoise": [0, 206, 209],
    "darkviolet": [148, 0, 211],
    "deeppink": [255, 20, 147],
    "deepskyblue": [0, 191, 255],
    "dimgray": [105, 105, 105],
    "dimgrey": [105, 105, 105],
    "dodgerblue": [30, 144, 255],
    "firebrick": [178, 34, 34],
    "floralwhite": [255, 250, 240],
    "forestgreen": [34, 139, 34],
    "fuchsia": [255, 0, 255],
    "gainsboro": [220, 220, 220],
    "ghostwhite": [248, 248, 255],
    "gold": [255, 215, 0],
    "goldenrod": [218, 165, 32],
    "gray": [128, 128, 128],
    "green": [0, 128, 0],
    "greenyellow": [173, 255, 47],
    "grey": [128, 128, 128],
    "honeydew": [240, 255, 240],
    "hotpink": [255, 105, 180],
    "indianred": [205, 92, 92],
    "indigo": [75, 0, 130],
    "ivory": [255, 255, 240],
    "khaki": [240, 230, 140],
    "lavender": [230, 230, 250],
    "lavenderblush": [255, 240, 245],
    "lawngreen": [124, 252, 0],
    "lemonchiffon": [255, 250, 205],
    "lightblue": [173, 216, 230],
    "lightcoral": [240, 128, 128],
    "lightcyan": [224, 255, 255],
    "lightgoldenrodyellow": [250, 250, 210],
    "lightgray": [211, 211, 211],
    "lightgreen": [144, 238, 144],
    "lightgrey": [211, 211, 211],
    "lightpink": [255, 182, 193],
    "lightsalmon": [255, 160, 122],
    "lightseagreen": [32, 178, 170],
    "lightskyblue": [135, 206, 250],
    "lightslategray": [119, 136, 153],
    "lightslategrey": [119, 136, 153],
    "lightsteelblue": [176, 196, 222],
    "lightyellow": [255, 255, 224],
    "lime": [0, 255, 0],
    "limegreen": [50, 205, 50],
    "linen": [250, 240, 230],
    "magenta": [255, 0, 255],
    "maroon": [128, 0, 0],
    "mediumaquamarine": [102, 205, 170],
    "mediumblue": [0, 0, 205],
    "mediumorchid": [186, 85, 211],
    "mediumpurple": [147, 112, 216],
    "mediumseagreen": [60, 179, 113],
    "mediumslateblue": [123, 104, 238],
    "mediumspringgreen": [0, 250, 154],
    "mediumturquoise": [72, 209, 204],
    "mediumvioletred": [199, 21, 133],
    "midnightblue": [25, 25, 112],
    "mintcream": [245, 255, 250],
    "mistyrose": [255, 228, 225],
    "moccasin": [255, 228, 181],
    "navajowhite": [255, 222, 173],
    "navy": [0, 0, 128],
    "oldlace": [253, 245, 230],
    "olive": [128, 128, 0],
    "olivedrab": [107, 142, 35],
    "orange": [255, 165, 0],
    "orangered": [255, 69, 0],
    "orchid": [218, 112, 214],
    "palegoldenrod": [238, 232, 170],
    "palegreen": [152, 251, 152],
    "paleturquoise": [175, 238, 238],
    "palevioletred": [216, 112, 147],
    "papayawhip": [255, 239, 213],
    "peachpuff": [255, 218, 185],
    "peru": [205, 133, 63],
    "pink": [255, 192, 203],
    "plum": [221, 160, 221],
    "powderblue": [176, 224, 230],
    "purple": [128, 0, 128],
    "red": [255, 0, 0],
    "rosybrown": [188, 143, 143],
    "royalblue": [65, 105, 225],
    "saddlebrown": [139, 69, 19],
    "salmon": [250, 128, 114],
    "sandybrown": [244, 164, 96],
    "seagreen": [46, 139, 87],
    "seashell": [255, 245, 238],
    "sienna": [160, 82, 45],
    "silver": [192, 192, 192],
    "skyblue": [135, 206, 235],
    "slateblue": [106, 90, 205],
    "slategray": [112, 128, 144],
    "slategrey": [112, 128, 144],
    "snow": [255, 250, 250],
    "springgreen": [0, 255, 127],
    "steelblue": [70, 130, 180],
    "tan": [210, 180, 140],
    "teal": [0, 128, 128],
    "thistle": [216, 191, 216],
    "tomato": [255, 99, 71],
    "turquoise": [64, 224, 208],
    "violet": [238, 130, 238],
    "wheat": [245, 222, 179],
    "white": [255, 255, 255],
    "whitesmoke": [245, 245, 245],
    "yellow": [255, 255, 0],
    "yellowgreen": [154, 205, 50]
}
